/*
 * each bot is fed one object chosen from the set below
 */
export default [
  {
    pair: "BTCUSDT",
    from: 30000,
    to: 40000,
    handCount: null,
    handSpan: 0.15,
    shrinkByPercent: 0,
    handSpanAfterShrinkage: null,
    quoteStartAmount: 100,
    quoteStartAmountPerHand: null,
    exchangeFee: 0.001,
    id: null,
    itsAccountId: null,
  },
  {
    pair: "BTCUSDT",
    from: 35000,
    to: 45000,
    handCount: null,
    handSpan: 1000,
    shrinkByPercent: 10,
    handSpanAfterShrinkage: null,
    quoteStartAmount: 100,
    quoteStartAmountPerHand: null,
    exchangeFee: 0.001,
    id: null,
    itsAccountId: null,
  },
  {
    pair: "BTCUSDT",
    from: 35000,
    to: 45000,
    handCount: null,
    handSpan: 1000,
    shrinkByPercent: 10,
    handSpanAfterShrinkage: null,
    quoteStartAmount: 100,
    quoteStartAmountPerHand: null,
    exchangeFee: 0.001,
    id: null,
    itsAccountId: null,
  },
  {
    pair: "BTCUSDT",
    from: 35000,
    to: 45000,
    handCount: null,
    handSpan: 1000,
    shrinkByPercent: 10,
    handSpanAfterShrinkage: null,
    quoteStartAmount: 100,
    quoteStartAmountPerHand: null,
    exchangeFee: 0.001,
    id: null,
    itsAccountId: null,
  },
  {
    pair: "BTCUSDT",
    from: 35000,
    to: 45000,
    handCount: null,
    handSpan: 1000,
    shrinkByPercent: 10,
    handSpanAfterShrinkage: null,
    quoteStartAmount: 100,
    quoteStartAmountPerHand: null,
    exchangeFee: 0.001,
    id: null,
    itsAccountId: null,
  },
  {
    pair: "BTCUSDT",
    from: 35000,
    to: 45000,
    handCount: null,
    handSpan: 1000,
    shrinkByPercent: 10,
    handSpanAfterShrinkage: null,
    quoteStartAmount: 100,
    quoteStartAmountPerHand: null,
    exchangeFee: 0.001,
    id: null,
    itsAccountId: null,
  },
];
